[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
rentby = "R3NT11111111111111111111111111111111111111"

[programs.localnet]
rentby = "R3NT11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/tmp/deploy-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
