[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rentby = "4CA1RUwCX7RSAXLrqfjNX7QGyFDZxjPs2kfQz2UaDvr3"

[programs.localnet]
rentby = "HmRuwkcYtKaCmx1uXycwCrjVcYBH5o9KGNd6ZF3S6Eq3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "target/deploy/fee-payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
