services:
  - type: web
    name: rentby-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd api && npm install
    startCommand: cd api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SOLANA_RPC_URL
        value: https://api.devnet.solana.com
      - key: PROGRAM_ID
        value: HmRuwkcYtKaCmx1uXycwCrjVcYBH5o9KGNd6ZF3S6Eq3
    healthCheckPath: /health
